// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// rmwcs_solve
Rcpp::IntegerVector rmwcs_solve(Rcpp::List& graph, Rcpp::List& params);
RcppExport SEXP _mwcsr_rmwcs_solve(SEXP graphSEXP, SEXP paramsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List& >::type graph(graphSEXP);
    Rcpp::traits::input_parameter< Rcpp::List& >::type params(paramsSEXP);
    rcpp_result_gen = Rcpp::wrap(rmwcs_solve(graph, params));
    return rcpp_result_gen;
END_RCPP
}
