# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sa_solve <- function(instance, solver) {
    .Call('_mwcsr_sa_solve', PACKAGE = 'mwcsr', instance, solver)
}

solve_annealing <- function(network) {
    .Call('_mwcsr_solve_annealing', PACKAGE = 'mwcsr', network)
}

rmwcs_solve <- function(network, params) {
    .Call('_mwcsr_rmwcs_solve', PACKAGE = 'mwcsr', network, params)
}

